// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD16Gg5c2gj63HLtrCFarqPnAdYiDUT_lU',
    appId: '1:496211936875:web:0ef660348c62672101932e',
    messagingSenderId: '496211936875',
    projectId: 'fishmaster-87f88',
    authDomain: 'fishmaster-87f88.firebaseapp.com',
    storageBucket: 'fishmaster-87f88.firebasestorage.app',
    measurementId: 'G-VNFWNL852W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCid0fr2uCy9JA7UN3q2a_oDwzlfsKHJZA',
    appId: '1:496211936875:android:8a9d8e178dea3d7801932e',
    messagingSenderId: '496211936875',
    projectId: 'fishmaster-87f88',
    storageBucket: 'fishmaster-87f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDClQNvN_wUbipHNieacXEnVTjoh01Tyoo',
    appId: '1:496211936875:ios:cd8da307d4969ee401932e',
    messagingSenderId: '496211936875',
    projectId: 'fishmaster-87f88',
    storageBucket: 'fishmaster-87f88.firebasestorage.app',
    iosBundleId: 'com.example.fishmaster',
  );

}