// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6haKKiYTUYreFK9CjfiVWm92_nBu2AI',
    appId: '1:881438887591:web:1211bf72b012413db5d582',
    messagingSenderId: '881438887591',
    projectId: 'fishmap-bf479',
    authDomain: 'fishmap-bf479.firebaseapp.com',
    storageBucket: 'fishmap-bf479.firebasestorage.app',
    measurementId: 'G-8FTDZKGLSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCvx0ULT8B8-I7hvGHjIVAz_KqyWVxAyU',
    appId: '1:881438887591:android:c5fc13d9610af822b5d582',
    messagingSenderId: '881438887591',
    projectId: 'fishmap-bf479',
    storageBucket: 'fishmap-bf479.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGRn311xH0SGel96NtGWYOj3Yhf_s59o',
    appId: '1:881438887591:ios:5a54d6392e8f868bb5d582',
    messagingSenderId: '881438887591',
    projectId: 'fishmap-bf479',
    storageBucket: 'fishmap-bf479.firebasestorage.app',
    iosBundleId: 'com.example.fishmaster',
  );
}
